### ISSUE TITLE
Support macOS

### ISSUE THREAD

**Issue by OskarGroth** [exyte/Grid#13]
It would be great if Grid could target support for macOS. It seems to support Catalyst, but that is not good enough for a native Mac app.

<img width="530" alt="Screenshot 2020-09-19 at 20 24 12" src="https://user-images.githubusercontent.com/1417019/93686493-f0d98300-fab6-11ea-893d-9a3447945d6f.png">

I took a stab at it and was able to add macOS support pretty easily. Unfortunately Xcode messes with so many project settings (and I don't know your preferred setup/naming) so it would probably be easier if you just addressed this on your end.

Steps to add Mac support:

1. Add macOS Framework target
2. Add all source files
3. Mac's dont have `didReceiveMemoryWarningNotification`. Find another solution for the layout cache.
4. Update `Package.swift` to add platform
5. Address some minor issues with examples using `UIColor` etc.
6. Done!

**Comment by denis-obukhov** [comment]
Thanks. This is a good suggestion

**Comment by denis-obukhov** [comment]
@OskarGroth Have you seen this error after opening any example view? 
```
=== AttributeGraph: cycle detected through attribute 246584 ===
Fatal error: file SwiftUI, line 0
2020-10-11 16:39:48.571830+0700 Mac_Grid_Example[15635:7419021] Fatal error: file SwiftUI, line 0
```
And how did you import Grid library to the example project? Cocoapods?

**Comment by denis-obukhov** [comment]
Added MacOS support in [v1.1.0](https://github.com/exyte/Grid/releases/tag/1.1.0)
Caching for MacOS TBD
