### ISSUE TITLE
WidgetKit issues due to ScrollView

### ISSUE THREAD

**Issue by t9mike** [exyte/Grid#15]
Hello. I using Grid for some iOS14 widgets. I am running into this:

<img width="258" alt="screenshot_2841" src="https://user-images.githubusercontent.com/1008514/101437483-ec628080-38d5-11eb-82b4-34a3bb23b7de.png">

SwiftUI is throwing up a warning per https://stackoverflow.com/questions/63135404/why-do-some-views-appear-as-a-red-no-entry-sign-in-widgets. The Grid's ScrollView was the issue.

I believe ScrollView would only be needed in .gridContentMode(.scroll) mode. As a quick hack I commented out the ScrollView in Grid and all seems good. 

I am fairly new to both Swift and SwiftUI as assume you would have a much more elegant real fix than I could provide. I won't need scrollable maybe ever for my project. But I could take a crack at a "real" fix.

Love the Grid! Thank you!!

**Comment by denis-obukhov** [comment]
@t9mike Thank you for the report! 
Please, try version [1.1.1.beta](https://github.com/exyte/Grid/releases/tag/1.1.1.beta)
Does this fix your issue?

**Comment by t9mike** [comment]
Wonderful! Thank you Denis.
