### ISSUE TITLE
Provide alignment option for cell

### ISSUE THREAD

**Issue by t9mike** [exyte/Grid#18]
I am still a SwiftUI newbie for sure, but I just could not figure out how to easily align cell contents, to change from centered. 

For example, in below I would like "A" to right align in the cell:

```
struct GridIssue2View: View {
    var body: some View {
        Grid(tracks: [
            .fit, // label
            .fit, // value
        ], spacing: 5)
        {
            Text("A")
            Text("B")
            Text("CCCCC")
            Text("D")
        }
        .frame(width: 100, height: 50)
        .border(Color.blue, width: 1)
    }
}
```
![image](https://user-images.githubusercontent.com/1008514/102038808-d51c0b00-3d8d-11eb-8320-4585e036e350.png)
I tried swapping out Text("A") with:
```
            HStack
            {
                Spacer()
                Text("A")
            }
```
Thinking that might push the A over. But it yielded:
 
![image](https://user-images.githubusercontent.com/1008514/102038910-17dde300-3d8e-11eb-8595-af886f25a997.png)

Thank you for any possible help!

**Comment by denis-obukhov** [comment]
Thanks for the feedback. Alignment for every item is defined with the Grid.
It would be nice to be able to specify an alignment for specific cells.
But for now, I've added `.gridItemsAlignment` modifier that changes alignment for all cells.
You could check [1.2.1.beta](https://github.com/exyte/Grid/releases/tag/1.2.1.beta) version. 
Is it useful for you?

**Comment by t9mike** [comment]
Hi Denis. In my case, I need **per cell**. I would right align column 1 and left align column 2. P.S. I use from source via fork so never a need to do a special release for me. Cheers.

**Comment by t9mike** [comment]
This works so I can use Lazy*Grid as needed I think:
```
struct LazyGrid1View: View {
    var body: some View {
        let cols = [GridItem(.flexible()),GridItem(.flexible())]
        LazyVGrid(columns:cols) {
            HStack {
                Spacer()
                Text("A")
            }
            HStack {
                Text("BBBBBBB")
                Spacer()
            }
            HStack {
                Spacer()
                Text("CCCCC")
            }
            HStack {
                Text("DDD")
                Spacer()
            }
        }
        .border(Color.blue, width: 1)
    }
}
```
![image](https://user-images.githubusercontent.com/1008514/102088265-4e444e00-3de0-11eb-8acf-eb48ee6b4a88.png)

**Comment by t9mike** [comment]
Here is the start of an extension to make this sort of thing easier for me.
```
public enum MakeAlignment {
    case Left
//    case Center
    case Right
//    case Top
//    case Middle
//    case Bottom
}

extension View
{
    public func makeAlign(_ alignment: MakeAlignment) -> some View {
        switch(alignment) {
            case .Left:
                return AnyView(HStack {
                    self
                    Spacer()
                })
            case .Right:
                return AnyView(HStack {
                    Spacer()
                    self
                })
        }
    }
}
```
And now:
```
struct LazyGrid2View: View {
    var body: some View {
        let cols = [GridItem(.flexible()),GridItem(.flexible())]
        LazyVGrid(columns:cols) {
            Text("A").makeAlign(.Right)
            Text("BBBBBBB").makeAlign(.Left)
            Text("CCCCC").makeAlign(.Right)
            Text("DDD").makeAlign(.Left)
        }
        .border(Color.blue, width: 1)
    }
}
```
Off to my (non-iOS) day job... Cheers.

**Comment by t9mike** [comment]
Unfortunately, LazyVGrid does not have "fit" column sizing so that is not useful without more work. 

I was trying to modify the code to make all GridTrack accept Alignment:
```
public enum GridTrack {
    case fr(CGFloat,Alignment)
    case pt(CGFloat,Alignment)
    case fit(Alignment)
```
This would support per-column alignment.

But I could not figure out how to extract this where I think it is used in Grid.swift near line 90:

![image](https://user-images.githubusercontent.com/1008514/102169342-95215a80-3e57-11eb-9cc6-7495f1b84229.png)
Any hints?

**Comment by denis-obukhov** [comment]
@t9mike I've brought new `.gridAlignment` modifier to align per item. It has higher priority than `.gridItemsAlignment` for the current item. 
Check [v1.3.1.beta](https://github.com/exyte/Grid/releases/tag/1.3.1.beta)
Here is usage for your case:

```
var body: some View {
    Grid(tracks: [
        .fit, // label
        .fit, // value
    ], spacing: 5)
    {
        Text("A").gridAlignment(.trailing)
        Text("B").gridAlignment(.trailing)
        Text("CCCCC").gridAlignment(.leading)
        Text("D").gridAlignment(.leading)
    }
    .frame(width: 100, height: 50)
    .border(Color.blue, width: 1)
}
```

<img width="114" alt="image" src="https://user-images.githubusercontent.com/63708833/102177300-d6f0e600-3ed5-11eb-8de2-30768e97b4af.png">

**Comment by t9mike** [comment]
Per cell alignment is much more powerful, general solution @denis-obukhov. Thank you. 

Any tips on how to get grid to size to "minimum size"? See nested example below where would want inner grid to be minimum size.
```
    var body: some View {
        Grid(tracks: [
            .fit, // label
            .fit, // value
        ], spacing: 5)
        {
            Text("A").gridAlignment(.trailing)
            Text("B").gridAlignment(.leading)
            Text("CCCCC").gridAlignment(.trailing)
            Text("D").gridAlignment(.leading)
            Text("Grid->").gridAlignment(.trailing)
            Grid(tracks: [
                .fit, // label
                .fit, // value
            ], spacing: 3) {
                Text("W").gridAlignment(.leading)
                Text("X").gridAlignment(.trailing)
                Text("YYYY").gridAlignment(.leading)
                Text("ZZZZ").gridAlignment(.trailing)
            }
            .border(Color.red, width: 1)
        }
        .border(Color.blue, width: 1)
    }
```
![image](https://user-images.githubusercontent.com/1008514/102220715-cf661880-3ea6-11eb-919a-45b75157d9ba.png)
