### ISSUE TITLE
Add Github Sponsor or other way to "tip"

### ISSUE THREAD

**Issue by t9mike** [exyte/Grid#19]
I would love to support development financially.

**Comment by ystrot** [comment]
Hi Mike!

Glad to hear you'd like to support development. However we're not trying to make money on the project and your activity already quite useful, thank you! If you'd like to do something else for the project, please just share it with your colleagues, we will be very grateful!

**Comment by t9mike** [comment]
Will do! I will be following development for sure and thank the team for the excellent work. I wish I was stronger in Swift/SwiftUI to jump into some issues that prevent some more advanced used cases, like nested Grid preference issue #16.
