### ISSUE TITLE
when the item count is 0 it align to center

### ISSUE THREAD

**Issue by yildirimatcioglu** [exyte/Grid#23]
Hello, I have a question about the layout. When item count is zero grid align to center. How to align it to leading? 
image: 
![Simulator Screen Shot - iPhone 12 - 2021-03-30 at 23 48 59](https://user-images.githubusercontent.com/17345325/113057042-4228a480-91b5-11eb-8d45-50bb05994621.png)

when count is not zero it is like this:
![Simulator Screen Shot - iPhone 12 - 2021-03-31 at 00 07 26](https://user-images.githubusercontent.com/17345325/113057086-4d7bd000-91b5-11eb-8c24-916fd354a89e.png)

**Comment by denis-obukhov** [comment]
Have a try [.gridContentAlignment ](https://github.com/exyte/Grid#11-alignment) modifier in the new v1.4.0
