### ISSUE TITLE
can not add views with if state of a @State boolean value

### ISSUE THREAD

**Issue by yildirimatcioglu** [exyte/Grid#24]
Hi, 
Adding view(ex: button ) with a if statement of a @State boolean value is not working inside of Grid with forEach. What can I do about it? Any idea?

**Comment by denis-obukhov** [comment]
@yildirimatcioglu Could you provide an example?

**Comment by f3dm76** [comment]
@yildirimatcioglu It's been a while, so I'll close this one for now. Please feel free to reopen if you are still having the issue.
