### ISSUE TITLE
Idea - No issue

### ISSUE THREAD

**Issue by SebastianBO** [exyte/Grid#3]
Like in the Fitbit app it would be nice to make them re-adjustable - going to use your library for showing dynamic data so would be an appreciated feature if you could move around the "block" on the Grid. 

Great library, thanks!

**Comment by denis-obukhov** [comment]
Thanks for the suggestion. Could you attach a screenshot of the Fitbit app with the corresponding screen?

**Comment by SebastianBO** [comment]
They have actually changed the UI to a List when I come to think of it now...🙄

**Comment by SebastianBO** [comment]
But I truly appreciate the fast response and that you would put effort into even entertaining this, thank you!
