### ISSUE TITLE
ScrollView Nesting Issues.

### ISSUE THREAD

**Issue by BenThomasClark** [exyte/Grid#34]
Hi,
I saw [this post ](https://github.com/exyte/Grid/issues/27) posted in October 2021 regarding issues with nesting the grids inside scroll views. And the answer was that scrollviews were not supported.

Is there any update on this or projected update release dates?

Thanks!

**Comment by brendand** [comment]
Have you tried setting `.gridContentMode(.scroll)`?

That'll put a scrollview around the grid.

**Comment by BenThomasClark** [comment]
Hi, yeah, that does work but only limited to the views scope - the grid I'm using needs to be part of a larger view, wrapped in a scrollView.
Thank you for your suggestion though.

**Comment by BenThomasClark** [comment]
Closing this issue now as after some investigation, this has been resolved/is invalid.
Anyone looking for an answer - you need to provide the ScrollView with a frame height and can be used in conjunction with a GeometryReader to provide a dynamic height based on content.

**Comment by GuilhermeDeconto** [comment]
> Closing this issue now as after some investigation, this has been resolved/is invalid.
> Anyone looking for an answer - you need to provide the ScrollView with a frame height and can be used in conjunction with a GeometryReader to provide a dynamic height based on content.

@BenThomasClark Could you provide a code snippet for this solution?

**Comment by BenThomasClark** [comment]
It would be something along the lines of:

`struct GridView: View {
    var body: some View {
        GeometryReader { gr in // <--- Height being calculated here
            ScrollView {
                    Grid(tracks: 2, spacing) {
                        ForEach(1..<99) { index in
                            Text("This is element \(index)")
                            }
                    }
                    .frame(minHeight: gr.size.height) // <--- Height being provided here
                }
            }
        }
    }
}`

**Comment by kiecooboi** [comment]
> > Closing this issue now as after some investigation, this has been resolved/is invalid.
> > Anyone looking for an answer - you need to provide the ScrollView with a frame height and can be used in conjunction with a GeometryReader to provide a dynamic height based on content.
> 
> @BenThomasClark Could you provide a code snippet for this solution?

```swift
        GeometryReader {
            let size = $0.size
            ScrollView {
                VStack {                    
                    Grid(tracks: 2) {
                        // ...
                    }
                }
                // .frame(width: size.width, height: size.height, alignment: .leading)  <- You can change the height here or just ignore this line, your `Gird` is now displayed in `ScrollView`
            }
            .scrollIndicators(.hidden)
        }
```
