### ISSUE TITLE
Urgent! - 1.4.2 build fails

### ISSUE THREAD

**Issue by thegalkin** [exyte/Grid#36]
Hi, 1.4.0 does build and 1.4.2 - doesn't - though didn't check 1.4.1
It fails to build as a project dependency and as a standalone project
Please see build log.
Environment - Xcode 13.4.1, macOS 12.4
[Build ExyteGrid_2023-01-23T02-08-12.txt](https://github.com/exyte/Grid/files/10475736/Build.ExyteGrid_2023-01-23T02-08-12.txt)

**Comment by denis-obukhov** [comment]
No longer relevant
