### ISSUE TITLE
Section Header

### ISSUE THREAD

**Issue by anoels** [exyte/Grid#5]
Is it possible to use the grid in scrollview with other views?

**Comment by denis-obukhov** [comment]
Wrapping the grid in the `ScrollView` for some reason leads to the `Bound preference *** tried to update multiple times per frame.` errors in console. So currently it's impossible. This is a good topic to think about.

**Comment by anoels** [comment]
Thank you for the information. I hope it would be possible in the near future.

**Comment by denis-obukhov** [comment]
Moved here #6
